/**
 * Regenerates every PNG in this folder from the live build.
 *
 * These images are generated by the app at build time, so this folder is a
 * snapshot and will go stale the moment the icon or card code changes. Rerun
 * after touching anything under `src/lib/og-*` or the icon routes.
 *
 *   npm run build
 *   npx next start -p 3111
 *   node brand-preview/render.mjs
 *
 * Pass a different port as the first argument if 3111 is taken.
 */
import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const PORT = process.argv[2] ?? "3111";
const BASE = `http://localhost:${PORT}`;
const OUT = dirname(fileURLToPath(import.meta.url));

/** route -> filename. Keep in step with the sections in index.html. */
const IMAGES = {
  "icon/16": "favicon-16",
  "icon/32": "favicon-32",
  "icon/48": "favicon-48",
  "apple-icon": "apple-touch-icon-180",
  "opengraph-image": "share-home-og",
  "twitter-image": "share-home-twitter",
  "projects/deepdarcy/opengraph-image": "share-project-deepdarcy",
  "projects/notschool/opengraph-image": "share-project-notschool",
  "projects/bharatsim/opengraph-image": "share-project-bharatsim",
};

let failed = 0;

for (const [route, name] of Object.entries(IMAGES)) {
  const url = `${BASE}/${route}`;
  try {
    const res = await fetch(url);
    if (!res.ok) {
      console.error(`  FAIL ${name} — ${res.status} from /${route}`);
      failed += 1;
      continue;
    }
    const bytes = Buffer.from(await res.arrayBuffer());
    await writeFile(join(OUT, `${name}.png`), bytes);
    console.log(`  ok   ${name}.png  (${bytes.length} bytes)`);
  } catch (err) {
    console.error(`  FAIL ${name} — ${err instanceof Error ? err.message : err}`);
    console.error(`       is the server running on ${BASE}?`);
    failed += 1;
  }
}

if (failed) {
  console.error(`\n${failed} image(s) failed.`);
  process.exit(1);
}
console.log("\nAll images written. Open brand-preview/index.html to view them.");
